CREATE DATABASE Trello
GO
USE Trello
GO
CREATE TABLE CARD(
	Id INT IDENTITY PRIMARY KEY,
	Titulo VARCHAR(100) NOT NULL,
	Etiqueta INT NOT NULL,
	DataInicio DATETIME NOT NULL,
	DataEntrega DATETIME NOT NULL
)
GO
CREATE TABLE CARDCOMENTARIO(
	ID INT IDENTITY PRIMARY KEY,
	IDCARD INT NOT NULL,
	CAIXATEXTO NVARCHAR(MAX),
	IDUSUARIO INT NOT NULL,
	DATAINICIO DATETIME NOT NULL,
	QUANTIDADEESTRELAS INT 
)
GO
CREATE TABLE USUARIO(
	ID INT IDENTITY PRIMARY KEY,
	LOGIN VARCHAR(100) NOT NULL,
	NOME VARCHAR(255) NOT NULL,
	SOBRENOME VARCHAR(255) NOT NULL,
	EMAIL VARCHAR(100) NOT NULL,
	CELULAR CHAR(11),
	BIOGRAFIA NVARCHAR(MAX)
)
